# -*- coding: utf-8 -*-
"""primer_proyecto_deportes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WRb6NZQkSIhEATar2c2wey0OyUfbX3u
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests
import joblib
from datetime import datetime, timedelta
from sklearn.preprocessing import LabelEncoder

# ── Page config ─────────────────────────────────────────────────────────────
st.set_page_config(page_title="UFC Value Bet Dashboard", layout="wide")

# ── Helpers ─────────────────────────────────────────────────────────────────

@st.cache_data
def load_history(path: str = 'ufc-master.csv') -> pd.DataFrame:
    """Load your historical fights CSV."""
    return pd.read_csv(path)

@st.cache_resource
def load_model_and_features():
    """Load the pretrained, calibrated model and feature list."""
    model = joblib.load('ufc_model.pkl')
    features = [
        'RedOdds','BlueOdds','RedExpectedValue','BlueExpectedValue',
        'WinStreakDif','LossDif','KODif','SubDif',
        'HeightDif','ReachDif','AgeDif'
    ]
    return model, features

@st.cache_data
def fetch_live_odds(api_key: str) -> list:
    """Fetch moneyline odds from the Odds API."""
    url = 'https://api.the-odds-api.com/v4/sports/mma_mixed_martial_arts/odds'
    params = {
        'apiKey': api_key,
        'regions': 'us',
        'markets': 'h2h',
        'oddsFormat': 'american'
    }
    resp = requests.get(url, params=params)
    resp.raise_for_status()
    return resp.json()

def implied_prob(o: float) -> float:
    """Convert American odds to implied probability."""
    return 100.0/(o+100.0) if o > 0 else abs(o)/(abs(o)+100.0)

# ── Main ────────────────────────────────────────────────────────────────────

def main():
    # Sidebar controls
    st.sidebar.header("Settings")
    api_key = st.sidebar.text_input("Odds API Key", type="password")
    edge_threshold = st.sidebar.slider("Edge Threshold (pp)", 0, 100, 15)
    days_ahead = st.sidebar.slider("Show events in next N days", 1, 30, 7)
    filter_str = st.sidebar.text_input("Filter matchups (comma-separated)")

    if not api_key:
        st.warning("Enter your Odds API key in the sidebar to continue.")
        return

    # Parse filters
    if filter_str and filter_str.strip():
        filters = [term.strip().lower() for term in filter_str.split(",") if term.strip()]
    else:
        filters = []

    st.title("UFC Value Bet Dashboard")

    # Load data & model
    df_hist = load_history()
    model, features = load_model_and_features()

    # Historical preview
    st.subheader("Historical Data Preview")
    st.dataframe(df_hist.head(5))

    # Fetch & display live odds
    st.subheader("Live Odds")
    events = fetch_live_odds(api_key)
    now = datetime.utcnow()
    cutoff = now + timedelta(days=days_ahead)

    odds_rows = []
    for ev in events:
        for bm in ev.get('bookmakers', []):
            markets = bm.get('markets', [])
            if not markets:
                continue
            mkt = markets[0]
            outcomes = mkt.get('outcomes', [])
            if len(outcomes) != 2:
                continue
            # parse fight time
            try:
                fight_time = datetime.fromisoformat(ev['commence_time'].replace('Z',''))
            except:
                continue
            if not (now <= fight_time <= cutoff):
                continue
            f1, f2 = outcomes[0]['name'], outcomes[1]['name']
            event_name = f"{f1} vs {f2}"
            if filters and not any(f in event_name.lower() for f in filters):
                continue
            odds_rows.append({
                'Event': event_name,
                'Time (UTC)': ev['commence_time'],
                f1: outcomes[0]['price'],
                f2: outcomes[1]['price']
            })

    df_odds = pd.DataFrame(odds_rows)
    if df_odds.empty:
        st.info("No upcoming fights match your criteria.")
        return
    st.dataframe(df_odds)

    # Compute value bets
    st.subheader(f"Value Bets (Edge ≥ {edge_threshold} pp)")
    value_bets = []
    for _, row in df_odds.iterrows():
        fighters = [c for c in row.index if c not in ['Event','Time (UTC)']]
        if len(fighters) != 2:
            continue
        f1, f2 = fighters
        o1, o2 = row[f1], row[f2]

        # find historical fight
        mask = (
            (df_hist['RedFighter'] == f1) & (df_hist['BlueFighter'] == f2)
        ) | (
            (df_hist['RedFighter'] == f2) & (df_hist['BlueFighter'] == f1)
        )
        hist = df_hist[mask]
        if hist.empty:
            continue
        idx = hist.index[0]
        probs = model.predict_proba(hist.loc[[idx], features])[0]

        for fighter, odds, side in [(f1, o1, 'Red'), (f2, o2, 'Blue')]:
            ip = implied_prob(odds)
            p  = probs[1] if side == 'Red' else probs[0]
            edge = (p - ip) * 100
            if edge >= edge_threshold:
                value_bets.append({
                    'Event': row['Event'],
                    'Fighter': fighter,
                    'Side': side,
                    'Odds': odds,
                    'Edge (pp)': round(edge, 1)
                })

    if value_bets:
        df_vb = pd.DataFrame(value_bets).sort_values('Edge (pp)', ascending=False)
        st.table(df_vb)
    else:
        st.info("No value bets meet your threshold.")

    # Staking strategy simulation
    st.subheader("Staking Strategy Simulation")
    BASE_EDGE, SAFE_EDGE = 5, 10
    BASE_STAKE, SAFE_STAKE = 0.02, 0.15
    bankroll = 10_000.0
    balances = []

    for vb in value_bets:
        frac = SAFE_STAKE if vb['Edge (pp)'] >= SAFE_EDGE else BASE_STAKE
        stake = bankroll * frac
        odds  = vb['Odds']
        payout = stake * (odds/100) if odds > 0 else stake * (100/abs(odds))
        # determine win by matching fighter & side to historical winner
        fight = vb['Event']
        fighter = vb['Fighter']
        side = vb['Side']
        winner = df_hist.loc[
            (df_hist['RedFighter'] == fighter) & (side == 'Red') |
            (df_hist['BlueFighter'] == fighter) & (side == 'Blue'),
            'Winner'
        ].values
        won = (len(winner) > 0 and winner[0] == side)
        profit = payout if won else -stake
        bankroll += profit
        balances.append(bankroll)

    if balances:
        chart_df = pd.DataFrame({'Bankroll': balances}, index=range(1, len(balances)+1))
        st.line_chart(chart_df)

    st.write(f"**Initial Bankroll:** $10,000")
    st.write(f"**Final Bankroll:** ${bankroll:,.2f}")
    st.write(f"**ROI:** {((bankroll-10_000)/10_000*100):.1f}%")

if __name__ == '__main__':
    main()