# -*- coding: utf-8 -*-
"""primer_proyecto_deportes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WRb6NZQkSIhEATar2c2wey0OyUfbX3u
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

def expected_value(prob, odds):
    return prob * (odds - 1) - (1 - prob)

# --- Map your CSV columns to model's expected names here ---
column_map = {
    'RedOdds': 'R_odds',
    'BlueOdds': 'B_odds',
    # Model expects these two, but they're not in your data; we add zeros below
    # 'RedExpectedValue': None,
    # 'BlueExpectedValue': None,
    'WinStreakDif': 'wins_total_diff',      # Example: adjust as needed
    'LossDif': 'losses_total_diff',         # Example: adjust as needed
    'KODif': 'kd_diff',
    'SubDif': 'sub_att_diff',               # or 'sub_avg_diff' - clarify!
    'HeightDif': 'height_diff',
    'ReachDif': 'reach_diff',
    'AgeDif': 'age_diff'
}

model_features = [
    'RedOdds', 'BlueOdds', 'RedExpectedValue', 'BlueExpectedValue',
    'WinStreakDif', 'LossDif', 'KODif', 'SubDif', 'HeightDif', 'ReachDif', 'AgeDif'
]

st.title("UFC Value Betting & Bankroll Simulator")

uploaded_model = st.file_uploader("Upload your model (.pkl)", type=["pkl"])
uploaded_data = st.file_uploader("Upload your dataset (.csv)", type=["csv"])

if uploaded_model and uploaded_data:
    model = joblib.load(uploaded_model)
    df = pd.read_csv(uploaded_data)

    # --- Rename columns to match model features ---
    for model_col, data_col in column_map.items():
        if data_col not in df.columns:
            st.warning(f"Column '{data_col}' (mapped for '{model_col}') is missing in your dataset.")
        else:
            df[model_col] = df[data_col]

    # --- Fill expected value columns with zero if missing ---
    for ev_col in ['RedExpectedValue', 'BlueExpectedValue']:
        if ev_col not in df.columns:
            df[ev_col] = 0.0

    # --- Double-check all model features present ---
    missing = [col for col in model_features if col not in df.columns]
    if missing:
        st.error(f"These columns are still missing after mapping: {missing}")
        st.stop()

    # --- Predict probabilities ---
    X = df[model_features]
    probs = model.predict_proba(X)[:, 1]
    df['RedProb'] = probs
    df['BlueProb'] = 1 - probs

    # --- Calculate expected values with real probabilities and odds ---
    df['RedExpectedValue'] = expected_value(df['RedProb'], df['RedOdds'])
    df['BlueExpectedValue'] = expected_value(df['BlueProb'], df['BlueOdds'])

    # --- Value bet threshold ---
    value_threshold = st.slider("Value bet threshold (%)", 1, 20, 5)
    value_threshold_decimal = value_threshold / 100

    red_value_bets = df[df['RedExpectedValue'] > value_threshold_decimal]
    blue_value_bets = df[df['BlueExpectedValue'] > value_threshold_decimal]

    st.header("Value Bets (Red)")
    st.dataframe(red_value_bets[['r_fighter', 'b_fighter', 'RedOdds', 'RedProb', 'RedExpectedValue']])

    st.header("Value Bets (Blue)")
    st.dataframe(blue_value_bets[['r_fighter', 'b_fighter', 'BlueOdds', 'BlueProb', 'BlueExpectedValue']])

    # --- Bankroll simulation ---
    st.header("Bankroll Simulation")
    initial_bankroll = st.number_input("Initial Bankroll ($)", 100, 100000, 1000, step=100)
    flat_bet_size = st.number_input("Flat Bet Size ($)", 1, 1000, 10, step=1)

    bets = []
    for _, row in red_value_bets.iterrows():
        bets.append({'fighter': row['r_fighter'], 'odds': row['RedOdds'], 'prob': row['RedProb'],
                     'ev': row['RedExpectedValue'], 'bet_side': 'Red', 'win': 1 if row['winner'] == 'Red' else 0})
    for _, row in blue_value_bets.iterrows():
        bets.append({'fighter': row['b_fighter'], 'odds': row['BlueOdds'], 'prob': row['BlueProb'],
                     'ev': row['BlueExpectedValue'], 'bet_side': 'Blue', 'win': 1 if row['winner'] == 'Blue' else 0})
    bets_df = pd.DataFrame(bets)

    # Simulate bankroll
    bankroll = [initial_bankroll]
    for i, row in bets_df.iterrows():
        result = flat_bet_size * (row['odds'] - 1) if row['win'] else -flat_bet_size
        bankroll.append(bankroll[-1] + result)
    bets_df['Bankroll'] = bankroll[1:]

    st.line_chart(bets_df['Bankroll'])

    st.header("Stats Summary")
    st.write(f"Total Bets: {len(bets_df)}")
    st.write(f"Wins: {bets_df['win'].sum()} / Losses: {len(bets_df) - bets_df['win'].sum()}")
    st.write(f"Final Bankroll: ${bankroll[-1]:.2f}")
    st.write(f"ROI: {((bankroll[-1] - initial_bankroll) / initial_bankroll) * 100:.2f}%")
    st.dataframe(bets_df)

else:
    st.info("Please upload both the model (.pkl) and the dataset (.csv).")