# -*- coding: utf-8 -*-
"""primer_proyecto_deportes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WRb6NZQkSIhEATar2c2wey0OyUfbX3u
"""

import streamlit as st
import pandas as pd
import joblib

st.title("UFC Value Bet Analyzer")

# Upload Model
st.sidebar.header("1. Upload Model")
uploaded_model = st.sidebar.file_uploader("Upload your trained UFC model (.pkl)", type=["pkl"])
if uploaded_model is not None:
    model = joblib.load(uploaded_model)
    st.sidebar.success("Model loaded successfully!")
else:
    st.warning("Please upload a trained UFC model (.pkl) file.")
    st.stop()

# Upload Data
st.sidebar.header("2. Upload Dataset")
uploaded_csv = st.sidebar.file_uploader("Upload your UFC dataset (.csv)", type=["csv"])
if uploaded_csv is not None:
    df = pd.read_csv(uploaded_csv)
    st.sidebar.success("Dataset loaded successfully!")
else:
    st.warning("Please upload a UFC dataset (.csv) file.")
    st.stop()

st.subheader("Dataset Columns")
st.write(df.columns.tolist())

st.subheader("First Rows of Dataset")
st.write(df.head())

# (You can now continue with your value bet and prediction logic below)
# For example:
if st.checkbox("Show dataset summary"):
    st.write(df.describe())

# TODO: Insert your prediction, value bet, bankroll simulation code here!

st.info("Ready to continue with value bet and bankroll simulation logic.")